import type { PublicAmenity, PublicApartmentCard, PublicApartmentDetail, PublicBuilding, PublicDeveloper, PublicProjectCard, PublicProjectDetail, PublicProjectImage, PublicApartmentImage, PublicApartmentProjectSummary } from '@/lib/catalog-contracts';

function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null; }
function requireRecord(value: unknown, context: string): Record<string, unknown> { if (!isRecord(value)) throw new TypeError(`Invalid catalog ${context}`); return value; }
function jsonString(value: unknown): string { if (value == null) return '[]'; if (typeof value === 'string') return value; try { return JSON.stringify(value); } catch { return '[]'; } }
function optionalString(value: unknown): string | undefined { return typeof value === 'string' && value.length > 0 ? value : undefined; }
function numeric(value: unknown): number | undefined { if (value == null) return undefined; const n = Number(value); return Number.isFinite(n) ? n : undefined; }

export function toPublicProjectImage(value: unknown): PublicProjectImage { const image = requireRecord(value, 'project image'); return { id: String(image.id), url: String(image.url), alt: optionalString(image.alt), altAr: optionalString(image.altAr), caption: optionalString(image.caption), captionAr: optionalString(image.captionAr), type: String(image.type ?? 'gallery'), order: Number(image.order ?? 0), width: numeric(image.width), height: numeric(image.height) }; }
export function toPublicApartmentImage(value: unknown): PublicApartmentImage { const image = requireRecord(value, 'apartment image'); return { id: String(image.id), url: String(image.url), alt: optionalString(image.alt), altAr: optionalString(image.altAr), caption: optionalString(image.caption), captionAr: optionalString(image.captionAr), type: String(image.type ?? 'gallery'), order: Number(image.order ?? 0), width: numeric(image.width), height: numeric(image.height) }; }
export function toPublicBuilding(value: unknown, apartmentCount = 0): PublicBuilding { const building = requireRecord(value, 'building'); return { id: String(building.id), slug: String(building.slug), projectId: String(building.projectId), name: String(building.name), nameAr: optionalString(building.nameAr), code: String(building.code), floors: Number(building.floors), hasElevator: Boolean(building.hasElevator), order: Number(building.order ?? 0), apartmentCount }; }
function toPublicAmenity(value: unknown): PublicAmenity { const amenity = requireRecord(value, 'amenity'); return { id: String(amenity.id), name: String(amenity.name), nameAr: optionalString(amenity.nameAr), icon: optionalString(amenity.icon), description: optionalString(amenity.description), descriptionAr: optionalString(amenity.descriptionAr) }; }
function toPublicDeveloper(value: unknown): PublicDeveloper { const developer = requireRecord(value, 'developer'); return { id: String(developer.id), slug: String(developer.slug), name: String(developer.name), nameAr: optionalString(developer.nameAr), description: optionalString(developer.description), descriptionAr: optionalString(developer.descriptionAr), logo: optionalString(developer.logo), website: optionalString(developer.website) }; }
function toPublicApartmentProjectSummary(value: unknown): PublicApartmentProjectSummary { const project = requireRecord(value, 'apartment project summary'); return { id: String(project.id), slug: String(project.slug), name: String(project.name), city: String(project.city), district: String(project.district), hasElevator: Boolean(project.hasElevator), hasSecurity: Boolean(project.hasSecurity) }; }
function toPublicApartmentBuilding(value: unknown): Pick<PublicBuilding, 'id' | 'slug' | 'name' | 'code'> { const building = requireRecord(value, 'apartment building'); return { id: String(building.id), slug: String(building.slug), name: String(building.name), code: String(building.code) }; }

export function toPublicProjectCard(value: unknown, counts: { available: number; reserved: number }): PublicProjectCard {
  const project = requireRecord(value, 'project card');
  const image = Array.isArray(project.images) && project.images[0] ? requireRecord(project.images[0], 'project card image') : undefined;
  return { id: String(project.id), slug: String(project.slug), name: String(project.name), tagline: optionalString(project.tagline), city: String(project.city), district: String(project.district), projectType: String(project.projectType), status: String(project.status), latitude: numeric(project.latitude), longitude: numeric(project.longitude), startingPrice: numeric(project.startingPrice), priceOnRequest: Boolean(project.priceOnRequest), minSurface: numeric(project.minSurface), maxSurface: numeric(project.maxSurface), deliveryYear: numeric(project.deliveryYear), deliveryQuarter: optionalString(project.deliveryQuarter), apartmentTypes: jsonString(project.apartmentTypes), hasParking: Boolean(project.hasParking), hasElevator: Boolean(project.hasElevator), hasGarden: Boolean(project.hasGarden), hasPool: Boolean(project.hasPool), featured: Boolean(project.featured), image: image ? { id: String(image.id), url: String(image.url), alt: optionalString(image.alt), type: String(image.type ?? 'gallery') } : undefined, apartmentCount: Number(project._count && isRecord(project._count) && project._count.apartments != null ? project._count.apartments : 0), availableApartmentCount: counts.available, reservedApartmentCount: counts.reserved };
}

export function toPublicApartmentCard(value: unknown): PublicApartmentCard {
  const apartment = requireRecord(value, 'apartment card');
  return { id: String(apartment.id), slug: String(apartment.slug), projectId: String(apartment.projectId), buildingId: optionalString(apartment.buildingId), unitNumber: optionalString(apartment.unitNumber), apartmentType: String(apartment.apartmentType ?? apartment.type ?? 'F3'), typeName: String(apartment.typeName), typeNameAr: optionalString(apartment.typeNameAr), surface: numeric(apartment.surface) ?? 0, floor: numeric(apartment.floor), totalFloors: numeric(apartment.totalFloors), orientation: optionalString(apartment.orientation), bedrooms: numeric(apartment.bedrooms) ?? 0, bathrooms: numeric(apartment.bathrooms), balconies: numeric(apartment.balconies), balconySurface: numeric(apartment.balconySurface), hasParking: Boolean(apartment.hasParking ?? apartment.parking), parkingSpots: numeric(apartment.parkingSpots), hasTerrace: Boolean(apartment.hasTerrace), terraceSurface: numeric(apartment.terraceSurface), hasGarden: Boolean(apartment.hasGarden), gardenSurface: numeric(apartment.gardenSurface), status: String(apartment.status), price: numeric(apartment.price), priceOnRequest: Boolean(apartment.priceOnRequest), project: isRecord(apartment.project) ? toPublicApartmentProjectSummary(apartment.project) : undefined, building: isRecord(apartment.building) ? toPublicApartmentBuilding(apartment.building) : undefined };
}

export function toPublicApartmentDetail(value: unknown): PublicApartmentDetail {
  const apartment = requireRecord(value, 'apartment');
  return { ...toPublicApartmentCard(apartment), rooms: jsonString(apartment.rooms), description: optionalString(apartment.description), descriptionAr: optionalString(apartment.descriptionAr), features: jsonString(apartment.features), featuresAr: jsonString(apartment.featuresAr), published: Boolean(apartment.published), archived: Boolean(apartment.archived), order: Number(apartment.order ?? 0), project: isRecord(apartment.project) ? toPublicApartmentProjectSummary(apartment.project) : undefined, building: isRecord(apartment.building) ? toPublicBuilding(apartment.building) : undefined, images: Array.isArray(apartment.images) ? apartment.images.map(toPublicApartmentImage) : [] };
}

export function toPublicProjectDetail(value: unknown): PublicProjectDetail {
  const project = requireRecord(value, 'project');
  const apartments = Array.isArray(project.apartments) ? project.apartments.map(toPublicApartmentDetail) : [];
  const buildingCounts = new Map<string, number>();
  for (const apartment of apartments) if (apartment.buildingId) buildingCounts.set(apartment.buildingId, (buildingCounts.get(apartment.buildingId) ?? 0) + 1);
  const buildings = Array.isArray(project.buildings) ? project.buildings.map(building => { const record = requireRecord(building, 'building'); return toPublicBuilding(record, buildingCounts.get(String(record.id)) ?? 0); }) : [];
  return { id: String(project.id), slug: String(project.slug), name: String(project.name), nameAr: optionalString(project.nameAr), tagline: optionalString(project.tagline), taglineAr: optionalString(project.taglineAr), description: optionalString(project.description), descriptionAr: optionalString(project.descriptionAr), city: String(project.city), cityAr: optionalString(project.cityAr), district: String(project.district), districtAr: optionalString(project.districtAr), address: optionalString(project.address), addressAr: optionalString(project.addressAr), latitude: numeric(project.latitude), longitude: numeric(project.longitude), projectType: String(project.projectType), status: String(project.status), apartmentTypes: jsonString(project.apartmentTypes), minSurface: numeric(project.minSurface), maxSurface: numeric(project.maxSurface), deliveryYear: numeric(project.deliveryYear), deliveryQuarter: optionalString(project.deliveryQuarter), hasParking: Boolean(project.hasParking), hasElevator: Boolean(project.hasElevator), hasGarden: Boolean(project.hasGarden), hasPool: Boolean(project.hasPool), hasSecurity: Boolean(project.hasSecurity), hasClim: Boolean(project.hasClim), startingPrice: numeric(project.startingPrice), priceOnRequest: Boolean(project.priceOnRequest), featured: Boolean(project.featured), order: Number(project.order ?? 0), buildings, apartments, amenities: Array.isArray(project.amenities) ? project.amenities.map(toPublicAmenity) : [], images: Array.isArray(project.images) ? project.images.map(toPublicProjectImage) : [], developer: isRecord(project.developer) ? toPublicDeveloper(project.developer) : undefined };
}
