'use client';

import { useState, useMemo, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Calendar, Clock, CheckCircle2, User, Phone, Mail, MessageCircle, ChevronLeft, ChevronRight, Loader2, AlertCircle } from 'lucide-react';
import { LEAD_INTENTS, getWhatsAppUrl } from '@/lib/constants';
import { trackEvent } from '@/lib/analytics';
import type { Lead } from '@/lib/lead-contracts';

interface BookingCalendarProps { projectName: string; apartmentName?: string; }
const TIME_SLOTS = ['09:00','10:00','11:00','14:00','15:00','16:00'] as const;
const DAY_LABELS = ['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'] as const;
const MONTH_LABELS = ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'] as const;
type Step = 'date'|'time'|'form'|'success';
const bookingSchema=z.object({name:z.string().min(2,'Le nom est requis (min. 2 caractères)'),phone:z.string().min(10,'Numéro de téléphone invalide').regex(/^(\+213|0)[5-7]\d{8}$/,'Format algérien requis (ex: 0555123456)'),email:z.string().email('Email invalide').or(z.literal('')).optional()});
type BookingFormData=z.infer<typeof bookingSchema>;
function getDaysInMonth(year:number,month:number){return new Date(year,month+1,0).getDate();}
function getISODay(date:Date){const d=date.getDay();return d===0?6:d-1;}
function formatDateFR(date:Date){return `${DAY_LABELS[getISODay(date)]} ${date.getDate()} ${MONTH_LABELS[date.getMonth()]}`;}
export function BookingCalendar({projectName,apartmentName}:BookingCalendarProps){
 const [step,setStep]=useState<Step>('date'); const [selectedDate,setSelectedDate]=useState<Date|null>(null); const [selectedTime,setSelectedTime]=useState<string|null>(null); const [submitStatus,setSubmitStatus]=useState<'idle'|'loading'|'error'>('idle');
 const today=useMemo(()=>{const d=new Date();d.setHours(0,0,0,0);return d;},[]); const [viewYear,setViewYear]=useState(today.getFullYear()); const [viewMonth,setViewMonth]=useState(today.getMonth());
 const [utmParams,setUtmParams]=useState<Record<string,string>>({}); useEffect(()=>{if(typeof window==='undefined')return;const params=new URLSearchParams(window.location.search);const utm:Record<string,string>={};['utm_source','utm_medium','utm_campaign','utm_content','utm_term','gclid','fbclid'].forEach(k=>{const v=params.get(k);if(v)utm[k]=v;});setUtmParams(utm);},[]);
 const calendarDays=useMemo(()=>{const cells:(Date|null)[]=[];const days=getDaysInMonth(viewYear,viewMonth);for(let i=0;i<getISODay(new Date(viewYear,viewMonth,1));i++)cells.push(null);for(let d=1;d<=days;d++)cells.push(new Date(viewYear,viewMonth,d));return cells;},[viewYear,viewMonth]);
 const maxDate=useMemo(()=>{const d=new Date(today);d.setDate(d.getDate()+14);return d;},[today]); const disabled=(date:Date)=>date<today||date>maxDate||getISODay(date)===6;
 const {register,handleSubmit,formState:{errors}}=useForm<BookingFormData>({resolver:zodResolver(bookingSchema),defaultValues:{name:'',phone:'',email:''}});
 const onSubmit=async(data:BookingFormData)=>{setSubmitStatus('loading');const dateStr=selectedDate?formatDateFR(selectedDate):'';const lead:Lead={name:data.name,phone:data.phone,email:data.email||undefined,intent:LEAD_INTENTS.BOOK_VISIT,message:`Visite planifiée : ${dateStr} à ${selectedTime}`,projectName,apartmentName,pageUrl:typeof window!=='undefined'?window.location.href:undefined,utmSource:utmParams.utm_source,utmMedium:utmParams.utm_medium,utmCampaign:utmParams.utm_campaign,utmContent:utmParams.utm_content,utmTerm:utmParams.utm_term,gclid:utmParams.gclid,fbclid:utmParams.fbclid,referrer:typeof document!=='undefined'?document.referrer:undefined,source:'WEBSITE'};try{const res=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(lead)});if(!res.ok)throw new Error('submit');setStep('success');trackEvent('form_success',{form_id:'booking_calendar',intent:LEAD_INTENTS.BOOK_VISIT});}catch{setSubmitStatus('error');trackEvent('form_failure',{form_id:'booking_calendar',reason:'network_or_server_error'});}};
 const whatsappUrl=getWhatsAppUrl(`Bonjour, je souhaite planifier une visite pour le projet ${projectName}${apartmentName?` - appartement ${apartmentName}`:''}.`);
 if(step==='success')return <div className="flex flex-col items-center gap-3 py-8 text-center"><CheckCircle2 className="size-12 text-forest"/><h3 className="text-lg font-bold">Visite demandée</h3><p className="text-sm text-muted-foreground">Votre demande a bien été reçue.</p></div>;
 return <div className="w-full rounded-xl border border-forest/20 bg-white overflow-hidden"><div className="bg-forest px-4 py-3 flex items-center gap-2"><Calendar className="size-4 text-white"/><h3 className="text-sm font-semibold text-white">Planifier une visite</h3></div><div className="px-4 pt-3 pb-4"><p className="text-xs text-muted-foreground">{projectName}{apartmentName&&<> · {apartmentName}</>}</p>
 {step==='date'&&<><div className="flex items-center justify-between mb-3"><button type="button" disabled={viewYear===today.getFullYear()&&viewMonth===today.getMonth()} onClick={()=>viewMonth===0?(setViewMonth(11),setViewYear(y=>y-1)):setViewMonth(m=>m-1)}><ChevronLeft className="size-4"/></button><span className="text-sm font-semibold">{MONTH_LABELS[viewMonth]} {viewYear}</span><button type="button" disabled={viewYear>maxDate.getFullYear()||(viewYear===maxDate.getFullYear()&&viewMonth>=maxDate.getMonth())} onClick={()=>viewMonth===11?(setViewMonth(0),setViewYear(y=>y+1)):setViewMonth(m=>m+1)}><ChevronRight className="size-4"/></button></div><div className="grid grid-cols-7 gap-1">{DAY_LABELS.map(d=><div key={d} className="text-center text-[10px] text-muted-foreground">{d}</div>)}{calendarDays.map((date,i)=>date?<button key={date.toISOString()} type="button" disabled={disabled(date)} onClick={()=>{setSelectedDate(date);setSelectedTime(null);setStep('time');trackEvent('form_start',{form_id:'booking_calendar'});}} className="size-8 rounded-lg text-xs disabled:opacity-30 hover:bg-forest/10">{date.getDate()}</button>:<div key={`blank-${i}`}/>)}</div><p className="mt-2 text-[10px] text-muted-foreground text-center">Dimanches non disponibles</p></>}
 {step==='time'&&<><div className="mb-3 flex items-center justify-between"><button type="button" onClick={()=>{setStep('date');setSelectedTime(null)}} className="text-xs">← Retour</button><span className="text-sm font-semibold">{selectedDate&&formatDateFR(selectedDate)}</span></div><div className="grid grid-cols-3 gap-2">{TIME_SLOTS.map(time=><button key={time} type="button" onClick={()=>{setSelectedTime(time);setStep('form')}} className={`rounded-lg border px-3 py-2 text-sm ${selectedTime===time?'bg-forest text-white':'hover:bg-forest/5'}`}><Clock className="inline size-3 mr-1"/>{time}</button>)}</div></>}
 {step==='form'&&<form onSubmit={handleSubmit(onSubmit)} className="space-y-3"><div className="flex items-center justify-between"><button type="button" onClick={()=>setStep('time')} className="text-xs">← Retour</button><span className="text-xs text-muted-foreground">{selectedDate&&formatDateFR(selectedDate)} · {selectedTime}</span></div><div><label className="text-xs font-medium">Nom *</label><Input {...register('name')} placeholder="Votre nom"/></div>{errors.name&&<p className="text-xs text-destructive">{errors.name.message}</p>}<div><label className="text-xs font-medium">Téléphone *</label><Input {...register('phone')} placeholder="0555 12 34 56"/></div>{errors.phone&&<p className="text-xs text-destructive">{errors.phone.message}</p>}<div><label className="text-xs font-medium">Email</label><Input type="email" {...register('email')} placeholder="votre@email.com"/></div>{errors.email&&<p className="text-xs text-destructive">{errors.email.message}</p>}<Button type="submit" disabled={submitStatus==='loading'} className="w-full bg-forest text-white">{submitStatus==='loading'?<><Loader2 className="size-4 mr-2 animate-spin"/>Envoi...</>:'Confirmer la visite'}</Button>{submitStatus==='error'&&<p className="text-xs text-destructive"><AlertCircle className="size-3 inline mr-1"/>Impossible d'envoyer la demande.</p>}<a href={whatsappUrl} target="_blank" rel="noreferrer" className="block"><Button type="button" variant="outline" className="w-full"><MessageCircle className="size-4 mr-2"/>WhatsApp</Button></a></form>}
 </div></div>;
}
