'use client';
import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowLeft, ArrowRight, Building2, Calendar, Camera, Car, CheckCircle2, ChevronDown, Home, Layers, MapPin, Maximize, MessageCircle, Phone, Calculator, Shield, TreePine, Waves, Snowflake, ArrowUpFromLine } from 'lucide-react';
import { useRouter } from '@/lib/router';
import { useProject } from '@/lib/api';
import { ASAS, formatPrice, getPhoneUrl, getWhatsAppUrl } from '@/lib/constants';
import { StatusBadge } from '@/components/shared/StatusBadge';
import { ApartmentCard, ApartmentCardSkeleton } from '@/components/shared/ApartmentCard';
import { LeadForm } from '@/components/shared/LeadForm';
import { MortgageCalculator } from '@/components/shared/MortgageCalculator';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible';
import { Button } from '@/components/ui/button';
import { ProjectGallery } from '@/components/shared/ProjectGallery';
import { VideoSection, type VideoItem } from '@/components/shared/VideoPlayer';
import NeighborhoodInfo from '@/components/shared/NeighborhoodInfo';
import { FAQSection } from '@/components/shared/FAQSection';
import { ProjectMap } from '@/components/shared/ProjectMap';
import { Breadcrumbs } from '@/components/shared/Breadcrumbs';
import { EmptyState } from '@/components/shared/EmptyState';
import DeliveryTimeline from '@/components/shared/DeliveryTimeline';
import { ShareButton } from '@/components/shared/ShareButton';
import { JsonLd } from '@/components/seo/JsonLd';
import { projectSchema } from '@/lib/seo';
import type { ProjectImage } from '@/lib/types';

const AMENITY_ICONS: Record<string, typeof Car> = { parking: Car, elevator: ArrowUpFromLine, garden: TreePine, pool: Waves, security: Shield, clim: Snowflake };
const fadeUp = { hidden: { opacity: 0, y: 12 }, visible: { opacity: 1, y: 0, transition: { duration: 0.35 } } };
interface ProjectDetailPageProps { projectSlug: string; }

export default function ProjectDetailPageV2({ projectSlug }: ProjectDetailPageProps) {
  const router = useRouter();
  const { data: project, isLoading, error } = useProject(projectSlug);
  const [typeFilter, setTypeFilter] = useState('');
  const [videos, setVideos] = useState<VideoItem[]>([]);
  useEffect(() => { if (!project?.id) return; let cancelled = false; fetch(`/api/videos?projectId=${project.id}`).then((res) => res.ok ? res.json() : null).then((json) => { if (!cancelled && json) setVideos(json.data ?? []); }).catch(() => undefined); return () => { cancelled = true; }; }, [project?.id]);
  const apartmentTypes = useMemo(() => { if (!project) return [] as string[]; try { const parsed = project.apartmentTypes ? JSON.parse(project.apartmentTypes) : null; if (Array.isArray(parsed)) return parsed.filter(Boolean); } catch { /* use apartment records */ } return [...new Set((project.apartments ?? []).map((a: any) => a.apartmentType).filter(Boolean))]; }, [project]);
  if (isLoading) return <ProjectDetailSkeleton />;
  if (error || !project) return <main className="min-h-screen bg-ivory flex items-center justify-center px-4"><div className="max-w-md text-center py-20"><h1 className="text-2xl font-bold text-foreground mb-3">Projet introuvable</h1><p className="text-muted-foreground mb-6">Le projet demandé n'existe pas ou n'est plus disponible.</p><Button onClick={() => router.goProjects()}><ArrowLeft className="size-4" />Retour aux projets</Button></div></main>;

  const allApartments = project.apartments ?? [];
  const availableApartments = allApartments.filter((a: any) => a.status === 'AVAILABLE' || a.status === 'COMING_SOON');
  const filteredApartments = typeFilter ? availableApartments.filter((a: any) => a.apartmentType === typeFilter) : availableApartments;
  const galleryImages: ProjectImage[] = (project.images ?? []).filter((img) => ['gallery', 'exterior', 'interior', 'amenity', 'architecture'].includes(img.type) && Boolean(img.url)).sort((a, b) => a.order - b.order);
  const heroImage = project.images?.find((img) => img.type === 'hero' && img.url)?.url ?? project.images?.find((img) => img.type === 'gallery' && img.url)?.url ?? '';
  const whatsAppMessage = `Bonjour, je suis intéressé(e) par le projet ${project.name} à ${project.district}. Pouvez-vous me renseigner sur les disponibilités ?`;
  const scrollToInventory = () => document.getElementById('apartments')?.scrollIntoView({ behavior: 'smooth', block: 'start' });

  return <main className="min-h-screen bg-ivory pb-16 sm:pb-0">
    <JsonLd data={projectSchema({ name: project.name, description: project.description ?? undefined, district: project.district, city: project.city, address: project.address ?? undefined, latitude: project.latitude ?? undefined, longitude: project.longitude ?? undefined, startingPrice: project.startingPrice ?? undefined, priceOnRequest: project.priceOnRequest, deliveryYear: project.deliveryYear ?? undefined, deliveryQuarter: project.deliveryQuarter ?? undefined, apartmentTypes: project.apartmentTypes, heroImage: heroImage || undefined, amenities: project.amenities?.map((a) => a.name), ...(project.slug ? { slug: project.slug } : {}) })} />

    <section className="relative overflow-hidden bg-charcoal text-white">
      <div className="absolute inset-0">{heroImage ? <img src={heroImage} alt={project.name} className="h-full w-full object-cover" fetchPriority="high" /> : <div className="h-full w-full bg-charcoal" aria-hidden="true" />}<div className="absolute inset-0 bg-gradient-to-t from-charcoal via-charcoal/65 to-charcoal/20" /></div>
      <div className="relative mx-auto flex min-h-[560px] max-w-7xl items-end px-4 pb-10 pt-28 sm:min-h-[620px] sm:px-6 lg:px-8"><div className="w-full max-w-4xl">
        <Breadcrumbs items={[{ label: 'Projets', onClick: () => router.goProjects(), hashUrl: '/projects' }, { label: project.name, hashUrl: `/projects/${project.slug}` }]} />
        <button onClick={() => router.goProjects()} className="mb-5 inline-flex min-h-11 items-center gap-2 text-sm text-white/75 hover:text-white"><ArrowLeft className="size-4" />Retour aux projets</button>
        <div className="mb-4"><StatusBadge status={project.status} type="project" /></div>
        <h1 className="max-w-3xl text-4xl font-semibold tracking-tight sm:text-5xl lg:text-6xl">{project.name}</h1>
        {project.tagline && <p className="mt-4 max-w-2xl text-lg leading-7 text-white/75 sm:text-xl">{project.tagline}</p>}
        <div className="mt-4 flex flex-wrap items-center gap-x-5 gap-y-2 text-sm text-white/75"><span className="inline-flex items-center gap-2"><MapPin className="size-4" />{project.district}, {project.city}</span>{project.deliveryYear && <span className="inline-flex items-center gap-2"><Calendar className="size-4" />Livraison Q{project.deliveryQuarter} {project.deliveryYear}</span>}</div>
        <div className="mt-8 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div>{project.startingPrice && !project.priceOnRequest ? <><p className="text-sm text-white/60">À partir de</p><p className="mt-1 text-3xl font-semibold text-gold sm:text-4xl">{formatPrice(project.startingPrice)}</p></> : <p className="text-lg font-medium text-white">Prix sur demande</p>}<p className="mt-2 text-sm text-white/65">{availableApartments.length} lot{availableApartments.length > 1 ? 's' : ''} actuellement présenté{availableApartments.length > 1 ? 's' : ''}</p></div><div className="flex flex-col gap-2 sm:flex-row"><Button onClick={scrollToInventory} size="lg" className="min-h-12 bg-white px-6 text-charcoal hover:bg-white/90">Voir les disponibilités <ArrowRight className="size-4" /></Button><a href={getWhatsAppUrl(whatsAppMessage)} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md border border-white/30 bg-white/10 px-5 text-sm font-semibold text-white backdrop-blur-sm hover:bg-white/15"><MessageCircle className="size-4" />WhatsApp</a><ShareButton variant="full" className="min-h-12 border-white/30 text-white hover:bg-white/10" /></div></div>
      </div></div>
    </section>

    <section className="border-b border-border bg-white"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-y divide-border sm:grid-cols-3 lg:grid-cols-6 lg:divide-y-0">{[
      { icon: MapPin, label: 'Localisation', value: project.district || '—' }, { icon: Home, label: 'Type', value: project.projectType === 'RESIDENTIAL' ? 'Résidentiel' : project.projectType === 'MIXED_USE' ? 'Mixte' : project.projectType || '—' }, { icon: Building2, label: 'Lots', value: `${allApartments.length}` }, { icon: Maximize, label: 'Surface', value: project.minSurface && project.maxSurface ? `${project.minSurface}–${project.maxSurface} m²` : '—' }, { icon: Car, label: 'Parking', value: project.hasParking ? 'Prévu' : 'Non indiqué' }, { icon: Calendar, label: 'Livraison', value: project.deliveryYear ? `Q${project.deliveryQuarter || ''} ${project.deliveryYear}` : '—' },
    ].map((fact) => <div key={fact.label} className="flex min-h-[112px] flex-col justify-center gap-2 px-4 py-5 sm:px-5"><fact.icon className="size-5 text-forest" aria-hidden="true" /><span className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{fact.label}</span><span className="text-sm font-semibold text-foreground">{fact.value}</span></div>)}</div></section>

    <section className="bg-background px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-forest">Preuve visuelle</p><h2 className="mt-2 text-2xl font-semibold tracking-tight text-foreground sm:text-3xl">Le projet, en images</h2></div>{galleryImages.length > 0 && <span className="inline-flex shrink-0 items-center gap-2 rounded-full bg-forest/10 px-3 py-1.5 text-sm font-medium text-forest"><Camera className="size-4" />{galleryImages.length} photo{galleryImages.length > 1 ? 's' : ''}</span>}</div><ProjectGallery images={galleryImages} projectName={project.name} fallbackImage={heroImage || undefined} /></div></section>
    {videos.length > 0 && <section className="border-y border-border bg-sand/20 px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><VideoSection videos={videos} title="Voir le projet en vidéo" /></div></section>}
    {project.deliveryYear && project.deliveryQuarter && <section className="border-y border-border bg-white px-4 py-8 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><DeliveryTimeline deliveryYear={project.deliveryYear} deliveryQuarter={project.deliveryQuarter} status={project.status} projectName={project.name} /></div></section>}

    <section id="apartments" className="scroll-mt-20 bg-ivory px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-forest">Disponibilités</p><h2 className="mt-2 text-2xl font-semibold tracking-tight text-foreground sm:text-3xl">Choisissez le logement qui vous correspond</h2><p className="mt-3 text-muted-foreground">Comparez les lots actuellement présentés et ouvrez leur fiche pour consulter les informations détaillées.</p></div><div className="mt-6 flex flex-wrap items-center gap-2 border-y border-border py-4">{[{ key: '', label: 'Tous' }, ...apartmentTypes.map((type) => ({ key: type, label: type }))].map((tab) => { const count = tab.key ? availableApartments.filter((a: any) => a.apartmentType === tab.key).length : availableApartments.length; const active = typeFilter === tab.key; return <button key={tab.key || 'all'} onClick={() => setTypeFilter(tab.key)} aria-pressed={active} className={`min-h-11 rounded-md px-4 text-sm font-semibold transition-colors ${active ? 'bg-forest text-white' : 'bg-white text-foreground ring-1 ring-border hover:ring-forest/30'}`}>{tab.label}<span className="ml-1 opacity-70">{count}</span></button>; })}</div><div className="mt-5 flex flex-wrap gap-3 text-sm"><span className="inline-flex items-center gap-2 rounded-full bg-forest/10 px-3 py-1.5 font-medium text-forest"><span className="size-2 rounded-full bg-forest" />{allApartments.filter((a: any) => a.status === 'AVAILABLE').length} disponible{allApartments.filter((a: any) => a.status === 'AVAILABLE').length > 1 ? 's' : ''}</span><span className="inline-flex items-center gap-2 rounded-full bg-gold/10 px-3 py-1.5 font-medium text-gold"><span className="size-2 rounded-full bg-gold" />{allApartments.filter((a: any) => a.status === 'RESERVED').length} réservé{allApartments.filter((a: any) => a.status === 'RESERVED').length > 1 ? 's' : ''}</span>{allApartments.some((a: any) => a.status === 'COMING_SOON') && <span className="inline-flex items-center gap-2 rounded-full bg-sand px-3 py-1.5 font-medium text-foreground"><span className="size-2 rounded-full bg-charcoal/50" />{allApartments.filter((a: any) => a.status === 'COMING_SOON').length} à venir</span>}</div>{filteredApartments.length > 0 ? <motion.div initial="hidden" whileInView="visible" viewport={{ once: true }} variants={{ visible: { transition: { staggerChildren: 0.05 } } }} className="mt-7 grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-3">{filteredApartments.map((apt: any) => <motion.div key={apt.id} variants={fadeUp}><ApartmentCard apartment={apt} projectSlug={projectSlug} /></motion.div>)}</motion.div> : <div className="mt-7"><EmptyState icon={Building2} title="Aucun lot dans ce filtre" description="Modifiez le type sélectionné ou contactez ASAS pour être accompagné." size="sm" /></div>}</div></section>

    {(project.buildings?.length > 0 || project.amenities?.length > 0 || project.description) && <section className="bg-background px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.05fr_0.95fr]"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-forest">Comprendre le projet</p>{project.description && <><h2 className="mt-2 text-2xl font-semibold text-foreground">Une lecture claire du projet</h2><p className="mt-4 max-w-2xl whitespace-pre-line leading-7 text-muted-foreground">{project.description}</p></>}{project.buildings?.length > 0 && <div className="mt-7 grid gap-3 sm:grid-cols-2">{project.buildings.map((building: any) => <div key={building.id} className="rounded-xl border border-border bg-card p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-semibold text-foreground">{building.name}</h3><span className="rounded-md bg-forest/10 px-2 py-1 text-xs font-semibold text-forest">{building.code}</span></div><div className="mt-3 flex flex-wrap gap-3 text-sm text-muted-foreground"><span className="inline-flex items-center gap-1.5"><Layers className="size-4 text-forest" />{building.floors} étage{building.floors > 1 ? 's' : ''}</span>{building.hasElevator && <span className="inline-flex items-center gap-1.5"><ArrowUpFromLine className="size-4 text-forest" />Ascenseur</span>}</div></div>)}</div>}</div>{project.amenities?.length > 0 && <div><h2 className="text-2xl font-semibold text-foreground">Équipements & services</h2><div className="mt-5 grid grid-cols-1 gap-3 sm:grid-cols-2">{project.amenities.map((amenity: any) => { const Icon = amenity.icon ? AMENITY_ICONS[amenity.icon] ?? CheckCircle2 : CheckCircle2; return <div key={amenity.id} className="flex items-center gap-3 rounded-xl border border-border bg-card p-4"><div className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-forest/10"><Icon className="size-5 text-forest" /></div><span className="text-sm font-medium text-foreground">{amenity.name}</span></div>; })}</div></div>}</div></section>}
    <NeighborhoodInfo city={project.city} district={project.district} />
    <FAQSection project={project} />

    <section className="bg-ivory px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-forest">Localisation</p><h2 className="mt-2 text-2xl font-semibold text-foreground">Où se situe le projet ?</h2><div className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-xl border border-border bg-white p-6"><div className="flex items-start gap-3"><MapPin className="mt-0.5 size-5 shrink-0 text-forest" /><div><p className="font-semibold text-foreground">{project.district}, {project.city}</p>{project.address && <p className="mt-2 text-sm leading-6 text-muted-foreground">{project.address}</p>}</div></div></div><ProjectMap projects={project.latitude && project.longitude ? [{ slug: project.slug, name: project.name, status: project.status, district: project.district, city: project.city, latitude: project.latitude, longitude: project.longitude }] : []} singleProject /></div></div></section>

    {!project.priceOnRequest && project.startingPrice && <section className="bg-background px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><Collapsible><CollapsibleTrigger asChild><Button variant="outline" size="lg" className="min-h-12 gap-2 border-forest text-forest hover:bg-forest/5"><Calculator className="size-5" />Simuler un crédit<ChevronDown className="size-4" /></Button></CollapsibleTrigger><CollapsibleContent className="pt-6"><div className="max-w-2xl"><h2 className="text-2xl font-semibold text-foreground">Estimez votre financement</h2><p className="mt-2 text-muted-foreground">Simulation indicative à partir de {formatPrice(project.startingPrice)}. Les conditions réelles dépendent de votre dossier et de l'établissement financeur.</p><div className="mt-5"><MortgageCalculator defaultPrice={project.startingPrice} /></div></div></CollapsibleContent></Collapsible></div></section>}

    <section className="bg-forest px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[0.85fr_1.15fr] lg:items-start"><div className="text-white"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-white/60">Prochaine étape</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Besoin de vérifier qu'il s'agit du bon projet pour vous ?</h2><p className="mt-4 max-w-xl leading-7 text-white/70">Parlez à ASAS pour recevoir les informations disponibles, comparer les lots ou organiser la suite de votre recherche.</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><a href={getWhatsAppUrl(whatsAppMessage)} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md bg-[#25D366] px-5 text-sm font-semibold text-white hover:brightness-95"><MessageCircle className="size-5" />WhatsApp</a><a href={getPhoneUrl()} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md border border-white/30 px-5 text-sm font-semibold text-white hover:bg-white/10"><Phone className="size-4" />Appeler {ASAS.phone}</a></div></div><div className="rounded-2xl bg-white p-5 shadow-xl sm:p-7"><LeadForm projectId={project.id} projectName={project.name} showWhatsApp={false} showPhone={false} compact /></div></div></section>

    <div className="fixed inset-x-0 bottom-0 z-40 border-t border-border bg-background/95 px-3 py-2 backdrop-blur-md sm:hidden" style={{ paddingBottom: 'max(0.5rem, env(safe-area-inset-bottom))' }}><div className="flex gap-2"><Button onClick={scrollToInventory} className="min-h-11 flex-[1.4] bg-forest text-white hover:bg-forest-dark">Disponibilités</Button><a href={getWhatsAppUrl(whatsAppMessage)} target="_blank" rel="noopener noreferrer" aria-label="Contacter ASAS sur WhatsApp" className="flex min-h-11 flex-1 items-center justify-center gap-1.5 rounded-md bg-[#25D366] text-sm font-semibold text-white"><MessageCircle className="size-4" />WhatsApp</a><a href={getPhoneUrl()} aria-label={`Appeler ${ASAS.phone}`} className="flex size-11 shrink-0 items-center justify-center rounded-md bg-charcoal text-white"><Phone className="size-4" /></a></div></div>
  </main>;
}
function ProjectDetailSkeleton() { return <main className="min-h-screen bg-ivory"><div className="h-[560px] shimmer-premium" /><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6">{[1,2,3,4,5,6].map((i) => <div key={i} className="h-28 border-b border-r border-border bg-white p-5"><div className="h-5 w-5 rounded bg-sand shimmer" /><div className="mt-3 h-3 w-16 rounded bg-sand shimmer" /><div className="mt-2 h-4 w-20 rounded bg-sand shimmer" /></div>)}</div><div className="mx-auto max-w-7xl px-4 py-12"><div className="h-8 w-64 rounded bg-sand shimmer-premium" /><div className="mt-4 aspect-video rounded-xl bg-sand shimmer-premium" /><div className="mt-12 grid grid-cols-1 gap-5 md:grid-cols-3">{[1,2,3].map((i) => <ApartmentCardSkeleton key={i} />)}</div></div></main>; }
